modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Turkey2349/BlockHighlighter/issues"
[[mods]]
    modId="blockhighlighter"
    version="1.2"
    displayName="Block Highlighter"
    displayURL="https://minecraft.curseforge.com/projects/block-highlighter"
    authors="Turkey2349"
    description='''
    Provides a QoL improvment of the vanilla block highlighting system!
    '''